/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.ClienteDAO;
import javax.swing.JOptionPane;
import negocio.Cliente;

/**
 *
 * @author Internet
 */
public class Cadastro_cliente extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Cadastro_cliente() {
        initComponents();
    }

    private void clearForm() {
        txtBairro.setText("");
        txtNome.setText("");
        txtCEP.setText("");
        txtCPF.setText("");
        txtCelular.setText("");
        txtEnderaco.setText("");
        txtNumero.setText("");
        txtTelefone.setText("");

    }

    private boolean validar() {

        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo Nome");
            return true;
        } else if (txtEnderaco.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo Endereço");
            return true;
        } else if (txtNumero.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo Numero");
            return true;
        } else if (txtBairro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo Bairro");
            return true;
        } else if (txtCPF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo CPF/CNPJ");
            return true;
        } else if (txtTelefone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo Telefone");
            return true;
        } else if (txtCelular.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo Celular");
            return true;
        } else if (txtCEP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo CEP");
            return true;
        }

        return false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        txtNome = new javax.swing.JTextField();
        txtEnderaco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtCEP = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnCancelar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnCancelar.setText("Voltar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(440, 230, 90, 30);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Cadastro Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 0, 230, 40);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 50, 15);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Celular:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 100, 50, 15);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CEP:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 130, 30, 15);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CNPJ", "CPF" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(10, 160, 70, 20);
        getContentPane().add(txtNome);
        txtNome.setBounds(90, 70, 250, 22);
        getContentPane().add(txtEnderaco);
        txtEnderaco.setBounds(90, 100, 250, 22);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Número:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 130, 60, 15);
        getContentPane().add(txtCelular);
        txtCelular.setBounds(420, 100, 110, 22);
        getContentPane().add(txtCEP);
        txtCEP.setBounds(420, 130, 110, 22);
        getContentPane().add(txtCPF);
        txtCPF.setBounds(90, 160, 130, 22);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 230, 100, 30);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Endereço:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 100, 70, 15);
        getContentPane().add(txtNumero);
        txtNumero.setBounds(90, 130, 70, 22);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefone:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 70, 70, 15);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(420, 70, 110, 22);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bairro:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 130, 50, 15);
        getContentPane().add(txtBairro);
        txtBairro.setBounds(220, 130, 120, 22);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDOLOGIN.jpg"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 540, 280);

        setSize(new java.awt.Dimension(556, 316));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new Controle().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (validar()) {
            return;
        }

        Cliente objCliente = new Cliente();
        ClienteDAO clienteBD = new ClienteDAO();
        clienteBD.inserir_Cliente(objCliente);

        objCliente.setNome(txtNome.getText());
        objCliente.setBairro(txtBairro.getText());
        objCliente.setEndereco(txtEnderaco.getText());
        objCliente.setCpf(txtCPF.getText());
        objCliente.setCelular(txtCelular.getText());
        objCliente.setCep(txtCEP.getText());
        objCliente.setNumero(txtNumero.getText());
        objCliente.setTelefone(txtTelefone.getText());

        if (clienteBD.inserir_Cliente(objCliente)) {
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!!!");
            clearForm();
        } else {
            JOptionPane.showMessageDialog(null, "Erro em adicionar o cliente!!!");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEnderaco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
