/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.ProdutosDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import negocio.Produtos;

/**
 *
 * @author Internet
 */
public class Consultar extends javax.swing.JFrame {

    /**
     * Creates new form Consultar
     */
    List<Produtos> listProdutos = new ArrayList<Produtos>();

    public Consultar() {
        initComponents();
        loadProdutos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadProdutos() {
        ProdutosDAO produtoBd = new ProdutosDAO();
        listProdutos = produtoBd.getListarProdutos();
        Object[] row = new Object[4]; // linha com 4 colunas;
        DefaultTableModel tabela = (DefaultTableModel) GridProdutos.getModel();
        tabela.setRowCount(0); //limpar os itens do grid

        //criando a ordem para ir para a tabela;
        for (Produtos item : listProdutos) {
            row[0] = item.getNome();
            row[1] = item.getCodigo();
            row[2] = item.getValor();
            row[3] = item.getQuantidade();
            tabela.addRow(row);
        }

    }

    public void pesquisaProduto(String nome) {
        Produtos objProduto = new Produtos();
        ProdutosDAO produtoBd = new ProdutosDAO();
        listProdutos = produtoBd.pesquisaProdutos(nome);
        Object[] row = new Object[4]; // linha com 4 colunas;
        DefaultTableModel tabela = (DefaultTableModel) GridProdutos.getModel();
        tabela.setRowCount(0); //limpar os itens do grid

        //criando a ordem para ir para a tabela;
        for (Produtos item : listProdutos) {
            row[0] = item.getNome();
            row[1] = item.getCodigo();
            row[2] = item.getValor();
            row[3] = item.getQuantidade();
            tabela.addRow(row);
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        GridProdutos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(667, 390));
        getContentPane().setLayout(null);

        GridProdutos.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        GridProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Produto", "Codigo do produto", "Valor do produto", "qtde produto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        GridProdutos.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(GridProdutos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 630, 260);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 310, 80, 30);
        getContentPane().add(txtPesquisar);
        txtPesquisar.setBounds(10, 10, 277, 22);

        jButton2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 10, 98, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDOLOGIN.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, 1, 650, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Controle().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (txtPesquisar.getText().isEmpty()) {
            loadProdutos();
            return;
        }
        pesquisaProduto(txtPesquisar.getText());

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GridProdutos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

    private void enableEdit() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
