/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.ProdutosDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.Produtos;

/**
 *
 * @author Default
 */
public class Deletar_produto extends javax.swing.JFrame {

    /**
     * Creates new form Deletar_produto
     */
    List<Produtos> listProdutos = new ArrayList<Produtos>();

    public Deletar_produto() {
        initComponents();
        loadProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadProdutos() {
        ProdutosDAO produtoBd = new ProdutosDAO();
        listProdutos = produtoBd.getListarProdutos();
        Object[] row = new Object[4]; // linha com 4 colunas;
        DefaultTableModel tabela = (DefaultTableModel) GridProdutos.getModel();
        tabela.setRowCount(0); //limpar os itens do grid

        //criando a ordem para ir para a tabela;
        for (Produtos item : listProdutos) {
            row[0] = item.getNome();
            row[1] = item.getCodigo();
            row[2] = item.getValor();
            row[3] = item.getQuantidade();
            tabela.addRow(row);
        }

    }

    private void clearForm() {
        txtCodigo.setText("");
        txtQuantidade.setText("");
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GridProdutos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(665, 450));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Movimento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 150, 20);

        lblCodigo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("Código: ");
        getContentPane().add(lblCodigo);
        lblCodigo.setBounds(20, 50, 52, 15);

        lblQuantidade.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantidade.setText("Quantidade: ");
        getContentPane().add(lblQuantidade);
        lblQuantidade.setBounds(20, 90, 82, 15);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(110, 50, 80, 22);
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(110, 90, 80, 22);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 120, 71, 23);

        btnDeletar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnDeletar.setText("Ok");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(200, 120, 60, 23);

        GridProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do produto", "Codigo do produto", "Valor do produto", "Qtde Produto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(GridProdutos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 620, 230);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDOLOGIN.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(2, -15, 650, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Controle().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        ProdutosDAO produtoBd = new ProdutosDAO();
        if (produtoBd.movimento(txtCodigo.getText(), txtQuantidade.getText())) {
            JOptionPane.showMessageDialog(null, "Produtos alterados com sucesso!!!");
            clearForm();
            loadProdutos();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao alterar o produto.");
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deletar_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deletar_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deletar_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deletar_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deletar_produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GridProdutos;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
