/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.ProdutosDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import negocio.Produtos;

/**
 *
 * @author Default
 */
public class Inserir_produto extends javax.swing.JFrame {

    /**
     * Creates new form Deletar_produto
     */
    List<Produtos> listProdutos = new ArrayList<Produtos>();

    public Inserir_produto() {
        initComponents();
    }

    private void clearForm() {
        txtQuantidade.setText("");
        txtNome.setText("");
        txtCodigo.setText("");
        txtValor.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 298));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inserir Produtos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 170, 23);

        lblNome.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome: ");
        getContentPane().add(lblNome);
        lblNome.setBounds(10, 60, 45, 15);

        lblCodigo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("Código: ");
        getContentPane().add(lblCodigo);
        lblCodigo.setBounds(10, 98, 52, 15);

        lblQuantidade.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantidade.setText("Quantidade: ");
        getContentPane().add(lblQuantidade);
        lblQuantidade.setBounds(10, 136, 82, 15);

        lblValor.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblValor.setForeground(new java.awt.Color(255, 255, 255));
        lblValor.setText("Valor: ");
        getContentPane().add(lblValor);
        lblValor.setBounds(10, 174, 42, 15);
        getContentPane().add(txtNome);
        txtNome.setBounds(111, 58, 160, 22);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(111, 96, 160, 22);
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(111, 134, 160, 22);
        getContentPane().add(txtValor);
        txtValor.setBounds(111, 172, 160, 22);

        btnInserir.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnInserir.setText("Inserir Produto");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir);
        btnInserir.setBounds(196, 210, 133, 23);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(335, 210, 71, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDOLOGIN.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -7, 440, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validar() {

        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo nome");
            return true;
        }
        if (txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo codigo");
            return true;
        }
        if (txtQuantidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo quantidade");
            return true;
        }
        if (txtValor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor preencher o campo valor");
            return true;
        }

        return false;

    }

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        if (validar()) {
            return;
        }

        Produtos objProduto = new Produtos();
        ProdutosDAO produtosBd = new ProdutosDAO();
        produtosBd.inserirProduto(objProduto);

        objProduto.setNome(txtNome.getText());
        objProduto.setCodigo(Integer.parseInt(txtCodigo.getText()));
        objProduto.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        objProduto.setValor(txtValor.getText());
        

        if (produtosBd.inserirProduto(objProduto)) {
            JOptionPane.showMessageDialog(null, "Produto inserido com sucesso!!!");
            clearForm();
        } else {
            JOptionPane.showMessageDialog(null, "Código do produto invalido!!!");
        }
    }//GEN-LAST:event_btnInserirActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Controle().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inserir_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inserir_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inserir_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inserir_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inserir_produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
